server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: http://192.168.42.233:8845
    gateway:
      routes:
        - id: user-service #路由标识
          uri: lb://userservice
          predicates: #判断路径匹配
            - Path=/user/**
          filters:
            - AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
        - id: order-service #路由标识
          uri: lb://Orderservice
          predicates: #判断路径匹配
            - Path=/order/**
#          filters:
#            - AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
